baseurl = "https://rexbianchi.com/"
title = "Rex Bianchi"
theme = 'hugo-theme-stack'
languageCode = "en-us"
paginate = 5


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"
